# Generated by Django 5.2.1 on 2025-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
