# Generated by Django 5.2.1 on 2025-05-19 09:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_aircraft_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base fare per seat in NZD', max_digits=8),
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price paid for this booking', max_digits=10, null=True),
        ),
    ]
