# Generated by Django 5.2.1 on 2025-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flightschedule_price_passenger_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='cust_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
